# Generated by Django 5.2.4 on 2025-07-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaContratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Área de Contratação')),
            ],
            options={
                'verbose_name': 'Área de Contratação',
                'verbose_name_plural': 'Áreas de Contratação',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da ocupação')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo (física ou jurídica)')),
            ],
            options={
                'verbose_name': 'Tipo de Pessoa',
                'verbose_name_plural': 'Tipos de Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('area_contratacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.areacontratacao', verbose_name='Área de Interesse')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
                ('ocupacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ocupacao', verbose_name='Ocupação')),
                ('tipo_pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipopessoa', verbose_name='Tipo de Pessoa')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_curriculo', models.URLField(verbose_name='Link do Currículo (Lattes)')),
                ('resumo', models.TextField(verbose_name='Resumo Profissional')),
                ('formacao', models.TextField(verbose_name='Formação Acadêmica')),
                ('experiencias', models.TextField(verbose_name='Experiências Profissionais')),
                ('habilidades', models.TextField(verbose_name='Habilidades')),
                ('ocupacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ocupacao', verbose_name='Ocupação Relacionada')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da vaga')),
                ('descricao', models.TextField(verbose_name='Descrição da vaga')),
                ('requisitos', models.TextField(verbose_name='Requisitos da vaga')),
                ('tipo', models.CharField(choices=[('Emprego', 'Emprego'), ('Estágio', 'Estágio')], max_length=10, verbose_name='Tipo da vaga')),
                ('area_contratacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.areacontratacao', verbose_name='Área de Contratação')),
                ('empresa', models.ForeignKey(limit_choices_to={'tipo_pessoa__nome': 'jurídica'}, on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateField(auto_now_add=True, verbose_name='Data da candidatura')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceita', 'Aceita'), ('Recusada', 'Recusada')], default='Pendente', max_length=10, verbose_name='Status')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vaga', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
            },
        ),
    ]
