# Generated by Django 5.2.4 on 2025-07-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vaga_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipopessoa', verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(limit_choices_to={'tipo_pessoa': 'jurídica'}, on_delete=django.db.models.deletion.CASCADE, to='app.empresa', verbose_name='Empresa'),
        ),
    ]
