# Generated by Django 5.2.4 on 2025-07-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empresa_tipo_pessoa_alter_vaga_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(limit_choices_to={'tipo_pessoa__nome': 'jurídica'}, on_delete=django.db.models.deletion.CASCADE, to='app.empresa', verbose_name='Empresa'),
        ),
    ]
